name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install PNPM globally
      run: npm install -g pnpm    

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm run build

    - name: Deploy to DigitalOcean App Platform
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        args: app create --spec .do/app-spec.yml
